typeidea/typeidea/urls.py
from django.contrib import admin
from django.urls import path,re_path
from .custom_site import  custom_site
from blog.views import PostDetailView,IndexView,CategoryView,TagView,SearchView,AuthorView
from config.views import  LinkListView
from comment.views import CommentView
from django.contrib.sitemaps import  views as sitemap_views
from blog.rss import  LatestPostFeed
from blog.sitemap import PostSiteMap
urlpatterns = [
    path('' ,IndexView.as_view(),name = 'index'),
    re_path(r'^search/$',SearchView.as_view(),name = 'search'),
    re_path(r'^author/(?P<author_id>\d+)/$',AuthorView.as_view(), name = "author"),
    re_path(r'^category/(?P<category_id>\d+)/$',CategoryView.as_view(), name='category-list'),
    re_path(r'^tag/(?P<tag_id>\d+)/$',TagView.as_view(),name = 'tag-list'),
    re_path(r'^post/(?P<post_id>\d+).html$',PostDetailView.as_view(),name = 'post-detail'),
    re_path(r'^links/$',LinkListView.as_view(),name='links'),
    re_path(r'^comment/$',CommentView.as_view(), name = 'comment'),
    re_path(r'^rss|feed/', LatestPostFeed(), name = 'rss'),
    re_path(r'^sitemap\.xml$',sitemap_views.sitemap,{'sitemaps': {'posts': PostSiteMap}}),
    path('super_admin/',admin.site.urls,name='super-admin'),
    path('admin/', custom_site.urls,name='admin'),
]

typeidea/comment/models.py
from django.db import models
from blog.models import Post
# Create your models here.

class Comment(models.Model):
    STATUS_NORMAL = 1
    STATUS_DELETE = 0
    STATUS_ITEMS = (
        (STATUS_NORMAL,"正常"),
        (STATUS_NORMAL,'删除'),
    )
    target = models.CharField(max_length=100, verbose_name="评论目标")
    content = models.CharField(max_length=2000,verbose_name="内容",)
    nickname = models.CharField(max_length=50, verbose_name="昵称")
    website = models.URLField(verbose_name="网站")
    email = models.EmailField(verbose_name="邮箱")
    status = models.PositiveIntegerField(choices=STATUS_ITEMS,verbose_name="状态",default=STATUS_NORMAL)
    created_time = models.DateTimeField(auto_now_add=True, verbose_name="创建时间")
    class Meta:
        verbose_name = verbose_name_plural = "评论"

    @classmethod
    def get_by_target(cls,target):
        return cls.objects.filter(target= target, status=cls.STATUS_NORMAL)

typeidea/comment/views.py
from django.shortcuts import render,HttpResponseRedirect,redirect
from django.views.generic import  TemplateView
from .form import CommentForm
# Create your views here.
class CommentView(TemplateView):
    http_method_names = ['post']
    template_name = 'comment/result.html'

    def post(self,request,*args, **kwargs):
        comment_form = CommentForm(request.POST)
        target = request.POST.get('target')

        if comment_form.is_valid():
            instance = comment_form.save(commit=False)
            instance.target = target ####不知道为什么不这样就不成了
            instance.save()
            succeed = True

        else:
            succeed = False
        context = {
            'succeed' : succeed,
            'form' : comment_form,
            'target' : target,
        }
        return self.render_to_response(context)

typeidea/typeidea/themes/bootstrap/templates/comment/block.html
<hr/>
<div class="comment">
    <form class = 'form-group' action="/comment/" method = 'POST'>
        {% csrf_token %}
        <input name = "target" type="hidden" value = "{{ target }}"/>
        {{ comment_form }}
        <input type = "submit" value = "写好了"/>
    </form>
    <! -- 评论列表 -- >
    <ul class = "list-group">
        {% for comment in comment_list %}
        <li class = "list-group-item">
            <div class="nickname">
                <a href=" {{ comment.website }} ">{{ comment.nickname }}</a>
                <span > {{ comment.created_time }}</span>

            </div>
            <div class="comment-content">
                {% autoescape off %}
                {{ comment.content }}
                {% endautoescape %}


            </div>
        </li>
        {% endfor %}

    </ul>
</div>

typeidea/typeidea/themes/bootstrap/templates/comment/result.html
<!doctype html>
<html>
<head>
    <title>
        评论结果页
    </title>
    <style>
        body {text-align: center;}
        .result {
            text-align: center;
            width: 40%;
            margin: auto;
        }
        .errorlist {color: red;}
        ul li {
            list-style-type: none;
        }
    </style>
</head>
<body>
<div class="result">
    {% if succeed %}
    评论成功
    <a href={{ target }}>返回</a>
    {% else %}
    <ul class = "errorlist">
        {% for field, message in form.errors.items %}
        <li>{{ message }}</li>
        {% endfor %}
    </ul>
    <a href="javascript:window.history.back();">返回</a>
    {% endif %}
</div>
</body>
</html>